### ISSUE TITLE
Injected DOM nodes result in React invariant failures

### ISSUE THREAD

**Issue by mihaip** [kwent/quiptree#1]
I'm a Quip engineer, and I was debugging some JS exceptions that some users were seeing, and traced it to this extension:

The `quiptree_toggle` and `quiptree_loader` `<span>`s that are appended to the `<nav>` element result in React getting confused about what is in the nav bar DOM, which leads to assertion failures when React re-renders it it. This extension was written before we rolled out our React-based web UI, so it's understandable that it wasn't written with that in mind.

We're going to be making a small code on our side change to remove the injected nodes from the DOM before they confuse React. I would suggest either injecting them into the `<body>` directly, or using a [page action](https://developer.chrome.com/extensions/pageAction) or other Chrome native UI.

**Comment by kwent** [comment]
@mihaip Well i think this extension is deprecated anyway since you guys implemented you own treeview

**Comment by mihaip** [comment]
Since users evidently still have it installed, would you mind releasing an update that either replaces the extension with a noop stub or uninstall itself (in the vein of https://plus.google.com/+FrancoisBeaufort/posts/j5q1hQ5Q85x)?

**Comment by kwent** [comment]
Unpublished from store.
